version: '3.7'
# 服务集合
services:
  # api-visual可视化服务
  api-visual:
    image: cheney/api-visual:latest
    volumes:
      - /root/.aws:/root/.aws #host_db:container_db
    ports:
      - "5000:5000"
    networks:
      - v1_overlay
    environment:
      - 'NODE_ENV=production'
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
  # 数据库
  db:
    image: mysql:latest
    volumes:
      - ./_db:/var/lib/mysql #host_db:container_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ab123456
    ports:
      - 3306:3306
    networks:
      - v1_overlay
    deploy:
      placement:
        constraints: [node.role == manager]
  # 数据库管理
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - v1_overlay
    deploy:
      placement:
        constraints: [node.role == manager]
# 网络集合
networks:
  v1_overlay:
