namespace: 'config'

attrs:  type,createdAt,flag,rangeHour

findOne:
    - select createdAt,flag,rangeHour,playerCreatedAt,lastMapTime from config where type = :type

updateFlag:
    - update config set flag = :flag where type = :type

updateOne:
    - update config set createdAt = :createdAt,flag = :flag where type = :type

updatePlayerCreatedAt:
    - update config set playerCreatedAt=:playerCreatedAt where type=:type

updateLastMapTime:
    - update config set lastMapTime=:lastMapTime where type=:type